=== discovered1086/XML-JSON-AND-JAVA/XMLSchemaProject/schema/student.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="http://www.example.org/student"
        xmlns:tns="http://www.example.org/student">
    
    <element name="student" type="tns:Student" />

    <complexType name="Student">
        <sequence>
            <element name="id" type="int" />
            <element name="name" type="string" />
            <element name="course" type="tns:course" />
            <element name="admissionYear" type="int" />
            <element name="email" type="string" maxOccurs="unbounded"/> <!--This makes the number of occurrences of
            this element unbounded-->
            <element name="address" type="tns:address" minOccurs="0"/> <!--This makes the element in the XML optional-->
            <element name="major" type="tns:Subjects" />
            <element name="minor" type="tns:MinorSubjects" />
        </sequence>
    </complexType>

    <simpleType name="course">
        <restriction base="string">
            <enumeration value="IT" />
            <enumeration value="CSE" />
            <enumeration value="MECH" />
            <enumeration value="AUE" />
            <enumeration value="ECE" />
        </restriction>
    </simpleType>

    <simpleType name="address">
        <restriction base="string" >
            <maxLength value="10" />
        </restriction>
    </simpleType>

    <complexType name="Subjects">
        <all>
            <element name="id" type="string" />
            <element name="Name" type="string" />
        </all>
    </complexType>

    <complexType name="MinorSubjects">
        <choice>
            <element name="Maths" type="tns:Subjects" />
            <element name="Automata" type="tns:Subjects" />
            <element name="HTML" type="tns:Subjects" />
        </choice>
    </complexType>
</schema>

=== discovered1086/XML-JSON-AND-JAVA/XMLSchemaProject/xml/student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tns:student xmlns:tns="http://www.example.org/student"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.example.org/student /schema/student.xsd" >
<tns:id>1</tns:id>
    <tns:name>Kingshuk</tns:name>
    <tns:course>MECH</tns:course>
    <tns:admissionYear>2005</tns:admissionYear>
    <tns:email>sly.mania42@gmail.com</tns:email>
    <tns:email>scorpion_kingshuk@yahoo.co.in</tns:email>
    <tns:email>kingshuk-2.mukherjee-2@cognizant.com</tns:email>
    <tns:major>
        <tns:id>123</tns:id>
        <tns:Name>Java</tns:Name>
    </tns:major>
    <tns:minor>
        <tns:Automata>
            <tns:id>12</tns:id>
            <tns:Name>Compiler programming</tns:Name>
        </tns:Automata>
    </tns:minor>
</tns:student>
